# Generated by Django 3.2 on 2021-04-29 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='release_date',
            new_name='dateRéalisation',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='director',
            new_name='intitulé',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='averageRating',
            new_name='nombreSorties',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='name',
            new_name='réalisateur',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='cast',
        ),
    ]
