# Generated by Django 3.2 on 2021-04-29 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='nombreSorties',
            field=models.FloatField(default=0),
        ),
    ]
