# Generated by Django 3.2 on 2021-04-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_movie_nombresorties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='nombreSorties',
            field=models.FloatField(default=0),
        ),
    ]
